events {}

http {

 upstream cyberguard_backend {
     server cyberguard-1:5000 max_fails=3 fail_timeout=5s;
     server cyberguard-2:5000 max_fails=3 fail_timeout=5s;
 }

 server {
     listen 80;

     location / {
         proxy_pass http://cyberguard_backend;
     }
 }
}