name: CI Pipeline

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:

  gitleaks:
    name: Gitleaks Scan
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  flake8-lint:
    name: Flake8 Lint
    runs-on: ubuntu-24.04
    needs: gitleaks
    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install flake8
        run: pip install flake8

      - name: Create flake8 config
        run: |
          echo "[flake8]" > .flake8
          echo "max-line-length = 120" >> .flake8

      - name: Run flake8
        run: flake8 . || true   # ne bloque pas le pipeline sur lint

  bandit-scan:
    name: SAST Bandit
    runs-on: ubuntu-24.04
    needs: flake8-lint
    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install Bandit
        run: pip install bandit

      - name: Run Bandit scan
        run: bandit -r .

      - name: Upload Bandit report
        uses: actions/upload-artifact@v4
        with:
          name: bandit-report
          path: bandit-report.json

  pip-audit:
    name: pip-audit security scan
    runs-on: ubuntu-24.04
    needs: bandit-scan
    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install pip-audit
        run: pip install pip-audit

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run pip-audit
        run: pip-audit
    
  trivy-unprebuild:
    name: Trivy Scan PreBuild
    runs-on: ubuntu-24.04
    needs: pip-audit
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          repository: Shrekye/CyberGuard
          ref: develop

      - name: Run Trivy filesystem scan
        uses: aquasecurity/trivy-action@0.35.0
        with:
          scan-type: fs
          format: table
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: os,library
          severity: CRITICAL,HIGH
          path: .

  trivy-postbuild:
    name: Trivy Scan – Post‑Build Docker Image
    runs-on: ubuntu-24.04
    needs: trivy-unprebuild
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image locally
        run: |
          docker build \
            -t cyberguard-local:${{ github.sha }} .

      - name: Run Trivy image scan
        uses: aquasecurity/trivy-action@v0.35.0
        with:
          image-ref: cyberguard-local:${{ github.sha }}
          format: table
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: os,library
          severity: CRITICAL,HIGH
  
dast-nikto:
  name: DAST Nikto Scan
  runs-on: ubuntu-24.04
  needs: trivy-postbuild
  steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build and run Docker container
      run: |
        docker build -t cyberguard:${{ github.sha }} .
        docker run -d --network host --name cyberguard-test cyberguard:${{ github.sha }}

    - name: Wait for Flask app to be ready
      run: |
        for i in {1..20}; do
          if curl -s http://localhost:5000 >/dev/null; then
            echo "App is ready!"
            break
          fi
          echo "Waiting for app to start..."
          sleep 1
        done

    - name: Install Nikto
      run: sudo apt-get update && sudo apt-get install -y nikto

    - name: Run Nikto scan
      run: nikto -h http://localhost:5000 -output nikto_report.txt

    - name: Upload Nikto report
      uses: actions/upload-artifact@v4
      with:
        name: nikto-report
        path: nikto_report.txt

    - name: Cleanup Docker container
      run: docker rm -f cyberguard-test

    dast-zap:
      name: owaspzap
      runs-on: ubuntu-24.04
      needs: trivy-unprebuild
      steeps:
        - name: Lancer app 
          run: |
            docker run -d\
            --name hackboard\
            -p 5000:5000\
            ${{secrets.DOCKERHUB_USERNAME}}/h
            ackboard:${{github.sha}}
            sleep 5

        - users: zaproxy/action-baseline@v0.12.0
          with:
            target:'http://127.0.0.1:5000'
            cmd_options:'-a'