name: CI Pipeline

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:

  gitleaks:
    name: Gitleaks Scan
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  flake8-lint:
    name: Flake8 Lint
    runs-on: ubuntu-24.04
    needs: gitleaks
    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install flake8
        run: pip install flake8

      - name: Create flake8 config
        run: |
          echo "[flake8]" > .flake8
          echo "max-line-length = 120" >> .flake8

      - name: Run flake8
        run: flake8 . || true   # ne bloque pas le pipeline sur lint

  bandit-scan:
    name: SAST Bandit
    runs-on: ubuntu-24.04
    needs: flake8-lint
    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install Bandit
        run: pip install bandit

      - name: Run Bandit scan
        run: bandit -r .

      - name: Upload Bandit report
        uses: actions/upload-artifact@v4
        with:
          name: bandit-report
          path: bandit-report.json

  pip-audit:
    name: pip-audit security scan
    runs-on: ubuntu-24.04
    needs: bandit-scan
    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install pip-audit
        run: pip install pip-audit

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run pip-audit
        run: pip-audit
    
  trivy-unprebuild:
    name: Trivy Scan PreBuild
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          repository: Shrekye/CyberGuard
          ref: develop

      - name: Run Trivy filesystem scan
        uses: aquasecurity/trivy-action@0.33.1
        with:
          scan-type: fs
          format: table
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: os,library
          severity: CRITICAL,HIGH
          path: .

  trivy-postbuild:
    name: Trivy Scan PostBuild Docker Image
    runs-on: ubuntu-24.04
    needs: trivy-unprebuild
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          repository: Shrekye/CyberGuard
          ref: develop

      - name: Build Docker image
        run: |
          docker build \
            -t docker.io/shrekye75/shrekye-project:4121c4ca19a0dd0465ca7a20f74dc7679788a98120f99485daf8bb18ccec0a6c .

      - name: Run Trivy image scan
        uses: aquasecurity/trivy-action@0.33.1
        with:
          image-ref: docker.io/shrekye75/shrekye-project:4121c4ca19a0dd0465ca7a20f74dc7679788a98120f99485daf8bb18ccec0a6c
          format: table
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: os,library
          severity: CRITICAL,HIGH